import { Inter } from 'next/font/google'

import { NavSidebar } from '@/components/layout/nav-sidebar'

import type { Metadata } from 'next'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="ja" data-theme="emerald">
            <body className={inter.className}>
                <div className="flex h-screen gap-10 p-8">
                    {children}
                    <NavSidebar />
                </div>
            </body>
        </html>
    )
}
